<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>WorldGen.Tests</RootNamespace>
    <AssemblyName>WorldGen.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WorldGen.Core\WorldGen.Core.csproj" />
    <ProjectReference Include="..\..\src\WorldGen.Persistence\WorldGen.Persistence.csproj" />
    <ProjectReference Include="..\..\src\WorldGen.Cli\WorldGen.Cli.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Link="README.md" Visible="false" />
  </ItemGroup>

</Project>
