<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>WorldGen.Persistence</RootNamespace>
    <AssemblyName>WorldGen.Persistence</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorldGen.Core\WorldGen.Core.csproj" />
  </ItemGroup>

</Project>
