<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WorldGen.Core\WorldGen.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>WorldGen.Adapter.Godot</RootNamespace>
    <AssemblyName>WorldGen.Adapter.Godot</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
